import React from 'react'


const About = () => {
  return (
    <div className='px-12 mt-[80px] leading-5 pl-[11rem] w-[1250px] '>
        <h1 className='tracking-[1px] font-adihapro font-CustomFont text-[30px] leading-[30px] mb-[10px] '>MEN'S SHOES</h1>
        <p className='tracking-[0.2px] font-adiha text-[16px] leading-[23px] mb-[16px]'>A pair of adidas shoes, for casual or sporting activities, is a must-have for men of all ages. A great way to finish off your outfit with style and look the part, no matter the occasion, is to choose your shoes wisely, and adidas is here to help with our range of shoes for men. Find the right sporting ally for you, with a wide range of men's shoes to choose from. No matter where your passions lie, you can find the right kicks to keep you performing at the ultimate level. The adidas range of men's shoes throws a nod to retro styles that created the brand's legacy and also looks at futuristic designs known for their tech backing and athlete-identical edge. Celebrity and sports star collaborations add that extra touch of class and swag when you step off the field or outside the gym and into your daily life. Worn by pro athletes, iconic public figures and celebrities alike, the 3-Stripes life leads you directly to success.</p>
        <h3 className='tracking-[1px] text-[20px] font-adihapro mt-5 mb-4'>SPORTING ESSENTIALS TO HELP YOU TRAIN LIKE A PRO</h3>
        <p className=' tracking-[0.2px]  font-adiha text-[16px] leading-[23px] mb-[16px]'>Choose your men's shoes with care, taking into consideration the return you want to see from your activity, whether for a day on the golf course, a training session for the next football season, a running plan for a marathon, or hiking in the mountains. The adidas range of shoes for men is designed using state-of-the-art technology and innovative features that will suit your exercise style. Football boots exist to play on soft ground with agility stud configuration, or hard ground with lightweight, firm ground outsoles. Up your game with a pair of football boots that hug your feet with a lightweight mesh upper. Golfers can choose shoes with a Primeknit upper that molds itself to your foot or a pair with a leather upper that keeps your feet warm and dry on cold, wet golf days. Challenge your personal best with a pair of adidas running shoes for men made with advanced Boost technology in the midsole that gives you extra lift with every step. Hikers, pick up a pair of lightweight GORE-TEX® shoes to keep your feet dry on rainy days.</p>
        <p className=' tracking-[0.2px] font-adiha text-[16px] leading-[23px] mb-[16px]'>Stand your ground on tricky surfaces when running trails, training on wet roads or ascending rock faces with the Continental rubber backing on soles of shoes. The perfect sole for a solid footing, look for the non-slip variants if your training days take you outdoors a lot. Basketball players can find low-cut shoes with superior EVA midsole cushioning that propels and supports for the highest dunks and jumps to keep them catching air without a weighted foot. Whatever your sporting vocation, there is a pair of adidas men's shoes that will prolong stamina, escalate performance and keep feet breathing no matter how long you need to wear them.</p>
        <h3 className='tracking-[1px] font-adihapro text-[20px] mt-5 mb-4'>NOT ONLY FOR TRAINING</h3>
        <p className=' tracking-[0.2px] font-adiha text-[16px] leading-[23px] mb-[16px]'>Relax after exercising by hanging out with your mates about town in an iconic pair of adidas casual sneakers with soft leather uppers and the iconic 3-Stripes boasting your loyalty to the brand. Alternatively, you can make a statement with a pair of retro trainers with a design based on the track shoes of the 1970s, with a nylon upper that remains true to the style of the time. With such a wide range of men's shoes by adidas, you will be sure to find the design, colour, and style that is right for you.</p>
        <p className=' tracking-[0.2px] font-adiha text-[16px] leading-[23px] mb-[16px]'>Putting together an outfit that has street cred, a fresh factor and a high-end touch is easy with adidas sneakers. Mix your shoes with chinos, jeans or long shorts for a lifestyle lived with the right attitude. Look for elevated pairs of trainers that add that touch of swag to a blazer and smart pants and bring an edginess into creative workspaces. No matter where your sneakers, trainers and shoes by adidas take you, you have a partner in comfort, performance and coolness.</p>
    </div>

  )
}

export default About