import React from "react";

const ProductData = [
    {
      id: 1,
      image: 'img-1.png',
      about: 'Bestseller',
      name: "Tatum 2 'Vortex' PF",
      category: "Basketball Shoes",
      colors: '2 Colour',
      price: '₹ 11,495.00',
    },
    {
      id: 2,
      image: 'img-2.png',
      about: 'Bestseller',
      name: "Air Jordan 4 Retro 'Industrial Blue'",
      category: "Men's Shoes",
      colors: '2 Colours',
      price: '₹ 19,499.00',
    },
    {
      id: 3,
      image: 'img-3.png',
      about: 'Bestseller',
      name: 'Nike Dunk Low',
      category: "Women's Shoes",
      colors: '3 Colours',
      price: '₹ 8,299.00',
    },
    {
      id: 4,
      image: 'img-4.png',
      about: 'Bestseller',
      name: 'Nike Court Vision Low',
      category: "Women's Shoes",
      colors: '1 Colour',
      price: '₹ 6,999.00',
    },
    {
      id: 5,
      image: 'img-5.png',
      about: 'Bestseller',
      name: 'Asics Gel-Kayano',
      category: "Women's Running Shoes",
      colors: '2 Colours',
      price: '₹ 10,499.00',
    },
    {
      id: 6,
      image: 'img-6.png',
      about: 'Bestseller',
      name: 'New Balance 574',
      category: "Men's Casual Shoes",
      colors: '4 Colours',
      price: '₹ 5,999.00',
    },
    {
      id: 7,
      image: 'img-7.png',
      about: 'Bestseller',
      name: 'Converse Chuck Taylor',
      category: "Unisex Shoes",
      colors: '6 Colours',
      price: '₹ 4,999.00',
    },
    {
      id: 8,
      image: 'img-8.png',
      about: 'Bestseller',
      name: 'Vans Old Skool',
      category: "Unisex Shoes",
      colors: '3 Colours',
      price: '₹ 3,999.00',
    },
    {
      id: 9,
      image: 'img-9.png',
      about: 'Bestseller',
      name: 'Under Armour HOVR Phantom',
      category: "Men's Running Shoes",
      colors: '2 Colours',
      price: '₹ 11,999.00',
    },
    {
      id: 10,
      image: 'img-10.png',
      about: 'Bestseller',
      name: 'Sketchers Go Walk',
      category: "Women's Casual Shoes",
      colors: '3 Colours',
      price: '₹ 3,499.00',
    },
    {
      id: 11,
      image: 'img-11.png',
      about: 'Bestseller',
      name: 'Nike Air Max Pulse Roam',
      category: "Men's Shoes",
      colors: '1 Colour',
      price: '₹ 8,295.00',
    },
    {
      id: 12,
      image: 'img-12.png',
      about: 'Bestseller',
      name: 'Adidas Ultraboost 21',
      category: "Men's Running Shoes",
      colors: '2 Colours',
      price: '₹ 12,999.00',
    },
    {
      id: 13,
      image: 'img-13.png',
      about: 'Bestseller',
      name: "Tatum 2 'Vortex' PF",
      category: "Basketball Shoes",
      colors: '2 Colour',
      price: '₹ 11,495.00',
    },
    {
      id: 14,
      image: 'img-14.png',
      about: 'Bestseller',
      name: "Air Jordan 4 Retro 'Industrial Blue'",
      category: "Men's Shoes",
      colors: '2 Colours',
      price: '₹ 19,499.00',
    },
    {
      id: 15,
      image: 'img-15.png',
      about: 'Bestseller',
      name: 'Nike Dunk Low',
      category: "Women's Shoes",
      colors: '3 Colours',
      price: '₹ 8,299.00',
    },
    {
      id: 16,
      image: 'img-16.png',
      about: 'Bestseller',
      name: 'Nike Court Vision Low',
      category: "Women's Shoes",
      colors: '1 Colour',
      price: '₹ 6,999.00',
    },{
      id: 17,
      image: 'img-17.png',
      about: 'Bestseller',
      name: "Tatum 2 'Vortex' PF",
      category: "Basketball Shoes",
      colors: '2 Colour',
      price: '₹ 11,495.00',
    },
    {
      id: 18,
      image: 'img-18.png',
      about: 'Bestseller',
      name: "Air Jordan 4 Retro 'Industrial Blue'",
      category: "Men's Shoes",
      colors: '2 Colours',
      price: '₹ 19,499.00',
    },
    {
      id: 19,
      image: 'img-19.png',
      about: 'Bestseller',
      name: 'Nike Dunk Low',
      category: "Women's Shoes",
      colors: '3 Colours',
      price: '₹ 8,299.00',
    },
    {
      id: 20,
      image: 'img-20.png',
      about: 'Bestseller',
      name: 'Nike Court Vision Low',
      category: "Women's Shoes",
      colors: '1 Colour',
      price: '₹ 6,999.00',
    },
    // Add more products as needed
  ];
  
  export default ProductData;
  